/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n pll_22579200 -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type pll -fin 22.579200 -clkibuf LVCMOS33 -fclkop 22.579200 -fclkop_tol 0.0 -fclkos 16.934400 -fclkos_tol 0.0 -phases 0 -fclkos2 90.316800 -fclkos2_tol 0.0 -phases2 0 -phase_cntl STATIC -fb_mode 1 -fdc C:/lscc/diamond/3.14/bin/nt64/pll_22579200/pll_22579200.fdc  */
/* Thu Oct 17 17:02:05 2024 */
`timescale 1 ns / 1 ps
`default_nettype none

module pll_22579200 (CLKI, CLKOP, CLKOS, CLKOS2)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLKI;
    output wire CLKOP;
    output wire CLKOS;
    output wire CLKOS2;

    wire REFCLK;
    wire LOCK;
    wire CLKOS2_t;
    wire CLKOS_t;
    wire CLKOP_t;
    wire buf_CLKI;
    //wire scuba_vhi;
    wire scuba_vlo;

    assign buf_CLKI = CLKI;
    assign scuba_vlo = 1'b0;

    //IB Inst1_IB (.I(CLKI), .O(buf_CLKI))
             /* synthesis IO_TYPE="LVCMOS33" */;

    //VHI scuba_vhi_inst (.Z(scuba_vhi));

    //VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam PLLInst_0.PLLRST_ENA = "DISABLED" ;
    defparam PLLInst_0.INTFB_WAKE = "DISABLED" ;
    defparam PLLInst_0.STDBY_ENABLE = "DISABLED" ;
    defparam PLLInst_0.DPHASE_SOURCE = "DISABLED" ;
    defparam PLLInst_0.CLKOS3_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS3_CPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_CPHASE = 5 ;
    defparam PLLInst_0.CLKOS_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS_CPHASE = 31 ;
    defparam PLLInst_0.CLKOP_FPHASE = 0 ;
    defparam PLLInst_0.CLKOP_CPHASE = 23 ;
    defparam PLLInst_0.PLL_LOCK_MODE = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.CLKOP_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOP_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.OUTDIVIDER_MUXD = "DIVD" ;
    defparam PLLInst_0.CLKOS3_ENABLE = "DISABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXC = "DIVC" ;
    defparam PLLInst_0.CLKOS2_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXB = "DIVB" ;
    defparam PLLInst_0.CLKOS_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXA = "DIVA" ;
    defparam PLLInst_0.CLKOP_ENABLE = "ENABLED" ;
    defparam PLLInst_0.CLKOS3_DIV = 1 ;
    defparam PLLInst_0.CLKOS2_DIV = 6 ;
    defparam PLLInst_0.CLKOS_DIV = 32 ;
    defparam PLLInst_0.CLKOP_DIV = 24 ;
    defparam PLLInst_0.CLKFB_DIV = 1 ;
    defparam PLLInst_0.CLKI_DIV = 1 ;
    defparam PLLInst_0.FEEDBK_PATH = "CLKOP" ;
    EHXPLLL PLLInst_0 (.CLKI(buf_CLKI), .CLKFB(CLKOP_t), .PHASESEL1(scuba_vlo),
        .PHASESEL0(scuba_vlo), .PHASEDIR(scuba_vlo), .PHASESTEP(scuba_vlo), 
        .PHASELOADREG(scuba_vlo), .STDBY(scuba_vlo), .PLLWAKESYNC(scuba_vlo), 
        .RST(scuba_vlo), .ENCLKOP(scuba_vlo), .ENCLKOS(scuba_vlo), .ENCLKOS2(scuba_vlo), 
        .ENCLKOS3(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(CLKOS_t), .CLKOS2(CLKOS2_t), 
        .CLKOS3(), .LOCK(LOCK), .INTLOCK(), .REFCLK(REFCLK), .CLKINTFB())
             /* synthesis FREQUENCY_PIN_CLKOS2="90.316800" */
             /* synthesis FREQUENCY_PIN_CLKOS="16.934400" */
             /* synthesis FREQUENCY_PIN_CLKOP="22.579200" */
             /* synthesis FREQUENCY_PIN_CLKI="22.579200" */
             /* synthesis ICP_CURRENT="10" */
             /* synthesis LPF_RESISTOR="8" */;

    assign CLKOS2 = CLKOS2_t;
    assign CLKOS = CLKOS_t;
    assign CLKOP = CLKOP_t;


    // exemplar begin
    // exemplar attribute Inst1_IB IO_TYPE LVCMOS33
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS2 90.316800
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS 16.934400
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOP 22.579200
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKI 22.579200
    // exemplar attribute PLLInst_0 ICP_CURRENT 10
    // exemplar attribute PLLInst_0 LPF_RESISTOR 8
    // exemplar end

endmodule
